### ISSUE TITLE
push-to-db/setup.py ne termine pas

### ISSUE THREAD

**Issue by avilleret** [mchobby/la-maison-pythonic#3]
bonjour :-)

j'ai un doute sur la ligne suivante : 
https://github.com/mchobby/la-maison-pythonic/blob/master/python/push-to-db/setup.sh#L32

en effet lorsqu'on exécute le script depuis une connexion SSH, cette ligne lance une nouvelle session dans le shell courant (ce que fait la commande `su -l ${USER}`)
j'ai alors une invite de commande qui se trouve dans le ${HOME}.
Je peux en sortir en tapant `exit` mais alors la fin du script n'est pas exécutée car la commande `exec` avec laquelle est démarrée cette nouvelle session quitte la session dans laquelle s'exécute le script.

Je ne comprends donc pas l'utilité de cette ligne, d'autant qu'elle empêche le script de se terminer normalement, qu'elle ne fait pas ce que le commentaire suggère et que si je la commente tout se passe bien :-)

**Comment by mchobby** [comment]
Bonjour,
A mon avis, vous avez rencontré le cas expliqué en page 609 du livre.
Le script attache l'utilisateur Pi à un groupe spécifique.
Mais cette assignation n'est pas immédiatement prise en compte dans le script et l'utilisateur couramment connecté n'a pas le droit d'effectuer les opérations qui suivent dans le script.
Il faut déconnecter l'utilisateur Pi réouvrir une nouvelle sessions et enfin relancer le script une seconde fois... cette fois là, cela devrait passer.
Cordialement,
Dominique

**Comment by avilleret** [comment]
Justement non, j'ai essayé de relancer le script plusieurs fois et à chaque fois j'ai eu le même comportement, même après un redémarrage.

**Comment by mchobby** [comment]
Je vais m'y repencher.

**Comment by mchobby** [comment]
La ligne `su -l ${USER})` a été ajouter pour forcer le rechargement des groupes de l'utilisateur Pi.
Mais ce qui fonctionne parfaitement dans le shell démarre une nouvelle session dans le script (diandre!).
En fait, celle ligne ne fait pas partie du livre! 

Effacez la ligne `su -l ${USER})` puis exécutez une deuxième fois le script en ayant pris soin de déloguer l'utilisateur entre les deux exécutions.
Je vais essayer de trouver une solution acceptable.

**Comment by mchobby** [comment]
Voilà c'est résolu et de façon plus élégante :-)
