### ISSUE TITLE
erreur schéma cabane

### ISSUE THREAD

**Issue by grapagnani** [mchobby/la-maison-pythonic#4]
Bonjour,
dans le schéma `esp8266/cabane/schema.png`, le bus SCL du Feather est connecté à la pin SDO du BMP280 au lieu de la pin SCK.

Schéma corrigé joint.
![schema](https://user-images.githubusercontent.com/24444/67710156-b5762780-f9bf-11e9-9189-23b79f7cce65.png)

**Comment by mchobby** [comment]
C'est corrigé.... merci :-)
