### ISSUE TITLE
à quoi sert la fonction heartbeat de la chaufferie ?

### ISSUE THREAD

**Issue by avilleret** [mchobby/la-maison-pythonic#5]
bonjour, 

d'après ce que je comprends la fonction `heartbeat` est appelée toutes les 10 sec (https://github.com/mchobby/la-maison-pythonic/blob/master/esp8266/chaufferie/main.py#L257)
et elle ne fait qu'attendre 200ms 
(https://github.com/mchobby/la-maison-pythonic/blob/master/esp8266/chaufferie/main.py#L220-L223)
je me demande donc à quoi elle sert ?

**Comment by mchobby** [comment]
Run_every eteind la LED à chaque fois que quelque-chose est exécuté (par exemple acquisition de donnée et publication sur MQTT) puis la rallume dès que cela est fini. Ces opérations standards sont assez rare dans la vie du projet (un fois par heure par exemple).... alors comment savoir que le code sur le microcontrôleur (et asyncio) est toujours en cours d'exécution ?
C'est le but de la tâche heartbeat... elle est appelée toutes les dix secondes par run_every. Et comme elle fait une pause de 200ms, cela aura pour effet d'éteindre la LED 200ms toutes les 10 secondes.... comme ça, on sait que le script (asynio) est toujours en cours d'exécution sur le microcontrôleur. 
Cette astuce s'est avéré bien pratique pour détecter rapidement un problème de stabilité fonctionnelle (même sans connexion REPL).

**Comment by avilleret** [comment]
ha ok ! je ne comprenais pas où la led était éteinte et allumée
merci pour la précision.
