### ISSUE TITLE
pourquoi les variables global à tout le script sont redéfinies global dans les functions ?

### ISSUE THREAD

**Issue by avilleret** [mchobby/la-maison-pythonic#6]
par exemple la variable `last_chaud_state_time` est taguée `global` ici : https://github.com/mchobby/la-maison-pythonic/blob/master/esp8266/chaufferie/main.py#L213

alors qu'elle est déjà définie dans le scope global à la ligne 44 https://github.com/mchobby/la-maison-pythonic/blob/master/esp8266/chaufferie/main.py#L44

la ligne 213 est donc superflue il me semble
dans tous les cas ce n'est pas bloquant, python est suffisamment souple, mais ça rend le code plus confu je trouve

**Comment by mchobby** [comment]
C'est propre à Python.... pour qu'une fonction puisse accéder à une variable global il faut lui indiquer, dans le corps de la fonction, que celle-ci est global.
Sinon Python créera une variable locale dans la fonction avec le même nom ;-)

**Comment by avilleret** [comment]
au temps pour moi... merci de la précision
